name: Build, Test & Deploy Docker Image

on:
  pull_request:
    branches: [ main, dev ]
  release:
    types: [ published ]
  push:
    branches: [ dev ]

env:
  IMAGE_NAME: polinux/ssh-ubuntu22
  REGISTRY: docker.io

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image for testing
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          load: true
          tags: ${{ env.IMAGE_NAME }}:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test Docker image
        run: |
          # Install dependencies for testing
          apt-get update && apt-get install -y sshpass
          
          echo "=== Testing basic functionality ==="
          # Test container starts successfully
          docker run -d --name test-container -p 2222:22 -e ROOT_PASWD=testpassword ${{ env.IMAGE_NAME }}:test
          sleep 10
          
          # Check if container is running
          if [ "$(docker ps -q -f name=test-container)" = "" ]; then
            echo "Container failed to start"
            docker logs test-container
            exit 1
          fi
          
          # Test SSH service is running
          docker exec test-container supervisorctl status sshd | grep RUNNING
          if [ $? -ne 0 ]; then
            echo "SSH service is not running"
            docker exec test-container supervisorctl status
            docker logs test-container
            exit 1
          fi
          
          # Test password was set correctly
          docker logs test-container | grep "Root password set to"
          if [ $? -ne 0 ]; then
            echo "Password initialization failed"
            docker logs test-container
            exit 1
          fi
          
          # Test SSH connectivity
          sshpass -p testpassword ssh -o StrictHostKeyChecking=no -p 2222 root@localhost "echo 'SSH connection successful'"
          if [ $? -ne 0 ]; then
            echo "SSH connection test failed"
            docker logs test-container
            exit 1
          fi
          
          # Clean up basic test
          docker stop test-container
          docker rm test-container
          
          echo "=== Testing user creation functionality ==="
          # Test user creation
          docker run -d --name test-user -p 2223:22 -e ROOT_PASWD=testpass -e USER=testuser ${{ env.IMAGE_NAME }}:test
          sleep 10
          
          # Check if user was created
          docker exec test-user id testuser
          if [ $? -ne 0 ]; then
            echo "User creation failed"
            docker logs test-user
            exit 1
          fi
          
          # Test user password logging
          docker logs test-user | grep "User.*password set to"
          if [ $? -ne 0 ]; then
            echo "User password logging failed"
            docker logs test-user
            exit 1
          fi
          
          # Test user password file
          docker exec test-user cat /data/logs/user-passwords.log | grep testuser
          if [ $? -ne 0 ]; then
            echo "User password file test failed"
            docker logs test-user
            exit 1
          fi
          
          # Get user password for SSH test
          USER_PASSWORD=$(docker exec test-user cat /data/logs/user-passwords.log | awk '{print $6}')
          echo "Testing SSH with user password: $USER_PASSWORD"
          
          # Test SSH connectivity as user
          sshpass -p "$USER_PASSWORD" ssh -o StrictHostKeyChecking=no -p 2223 testuser@localhost "echo 'User SSH connection successful'"
          if [ $? -ne 0 ]; then
            echo "User SSH connection test failed"
            docker logs test-user
            exit 1
          fi
          
          docker stop test-user
          docker rm test-user
          
          echo "=== Testing sudo functionality ==="
          # Test user creation with sudo
          docker run -d --name test-sudo -p 2224:22 -e ROOT_PASWD=testpass -e USER=sudouser -e USER_IN_SUDO=true ${{ env.IMAGE_NAME }}:test
          sleep 10
          
          # Check if user was added to sudo group
          docker exec test-sudo groups sudouser | grep sudo
          if [ $? -ne 0 ]; then
            echo "User sudo group test failed"
            docker logs test-sudo
            exit 1
          fi
          
          # Check sudo configuration file exists
          docker exec test-sudo cat /etc/sudoers.d/sudouser
          if [ $? -ne 0 ]; then
            echo "Sudo configuration file test failed"
            docker logs test-sudo
            exit 1
          fi
          
          # Test sudo functionality
          docker exec test-sudo su - sudouser -c "sudo whoami" | grep root
          if [ $? -ne 0 ]; then
            echo "Sudo functionality test failed"
            docker logs test-sudo
            exit 1
          fi
          
          # Test sudo logs
          docker logs test-sudo | grep "granted sudo privileges"
          if [ $? -ne 0 ]; then
            echo "Sudo logging test failed"
            docker logs test-sudo
            exit 1
          fi
          
          docker stop test-sudo
          docker rm test-sudo
          
          echo "=== All tests passed! ==="

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            network=host

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BUILDKIT_INLINE_CACHE=1
          timeout: 30m

      - name: Update Docker Hub description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ env.IMAGE_NAME }}
          short-description: "Ubuntu 22 SSH Docker Container - OpenSSH server with configurable passwords, user creation, sudo privileges, and comprehensive logging"
          readme-filepath: ./README.md